{% set name = "k9s" %}
{% set version = "0.32.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/derailed/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e011697b3de99d7691119036eaae6e5d4f1a98e284755ab6b15ae6daba08595f
    folder: src
  - url: https://raw.githubusercontent.com/xi2/xz/refs/heads/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    folder: xz-LICENSE-1
  - url: https://raw.githubusercontent.com/tukaani-project/xz/refs/heads/master/COPYING
    sha256: aedbbc280610875b83e246f05957369f84acf9abdb86b884a9ff2f5dd65e8ffb
    folder: xz-LICENSE-2
  - url: https://gitlab.com/cznic/mathutil/-/raw/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    folder: mathutil-LICENSE

build:
  script:
    - cd src
    - go-licenses save . --ignore github.com/derailed/popeye --ignore github.com/xi2/xz --ignore modernc.org/mathutil --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/k9s  # [not win]
    - go build -v -o %LIBRARY_BIN%\k9s.exe  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - k9s --help

about:
  home: https://k9scli.io
  summary: 🐶 Kubernetes CLI To Manage Your Clusters In Style!
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/LICENSE
    - library_licenses/
    - xz-LICENSE-1/LICENSE
    - xz-LICENSE-2/COPYING
    - mathutil-LICENSE/LICENSE
  dev_url: https://github.com/derailed/k9s
  doc_url: https://k9scli.io

extra:
  recipe-maintainers:
    - pavelzw
    - ytausch
