context:
  name: k9s
  version: 0.50.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/derailed/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 4f7f6702145b0eea2f42c684ff823aa261bc80b1a3b2a33b56fb6f87d7755c73
    target_directory: src
  - url: https://raw.githubusercontent.com/xi2/xz/refs/heads/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    target_directory: xz-LICENSE-1
  - url: https://raw.githubusercontent.com/tukaani-project/xz/refs/heads/master/COPYING
    sha256: 616a3ad264ce29b8f1cb97e53037b139d406899ca8d1f799651e17bfa09830b8
    target_directory: xz-LICENSE-2
  - url: https://gitlab.com/cznic/mathutil/-/raw/master/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    target_directory: mathutil-LICENSE

build:
  script:
    - cd src
    - go-licenses save . --ignore github.com/derailed/popeye --ignore github.com/xi2/xz --ignore modernc.org/mathutil --save_path ../library_licenses
    - if: win
      then: go build -v -o %LIBRARY_BIN%\k9s.exe
      else: go build -v -o $PREFIX/bin/k9s
  number: 1

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script: k9s --help

about:
  homepage: https://k9scli.io
  summary: 🐶 Kubernetes CLI To Manage Your Clusters In Style!
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
    - xz-LICENSE-1/LICENSE
    - xz-LICENSE-2/COPYING
    - mathutil-LICENSE/LICENSE
  repository: https://github.com/derailed/k9s
  documentation: https://k9scli.io

extra:
  recipe-maintainers:
    - pavelzw
    - ytausch
